sublet/app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^apartments/$', views.apartments, name='apartments'),
    url(r'^listings/$', views.listings, name='listings'),
    url(r'^listing/(?P<shard_id>[0-9]+)/(?P<list_id>[0-9]+)/$', views.listing, name='listing'),
    url(r'^bookings/$', views.bookings, name='bookings'),
    # url(r'^booking/$', views.booking, name='booking'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^addlisting/$', views.addListing, name='addListing'),
    url(r'^addapartment/$', views.addApartment, name='addApartment'),
    url(r'^editlisting/(?P<shard_id>[0-9]+)/(?P<list_id>[0-9]+)/$', views.editListing, name='editListing'),
    # url(r'^deletelisting/$', views.deleteListing, name='deleteListing'),
    url(r'^apartment/(?P<shard_id>[0-9]+)/(?P<apt_id>[0-9]+)/$', views.apartment, name='apartment'),
    url(r'^book/$', views.book, name='book'),
    url(r'^estimate/$', views.estimate, name='estimate'),
]

sublet/sublet/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^sublet/', include('app.urls', namespace='app')),
    url(r'^admin/', include(admin.site.urls)),
]

sublet/app/templates/app/addapartment.html
{% extends 'app/base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="container center">
            <h2>Add Apartment</h2>
            <form action="{% url 'app:addApartment' %}" method="post">
            {% csrf_token %}
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="street">Street</label>
                        <input type="text" name="street" id="street">
                    </div>
                </div>
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="city">City</label>
                        <input type="text" name="city" id="city">
                    </div>
                </div>
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="state">State</label>
{#                <input type="text" name="state" id="state">#}
                        <select name="state" id="state" class="browser-default">
                            <option value="AL">Alabama</option>
                            <option value="AK">Alaska</option>
                            <option value="AZ">Arizona</option>
                            <option value="AR">Arkansas</option>
                            <option value="CA">California</option>
                            <option value="CO">Colorado</option>
                            <option value="CT">Connecticut</option>
                            <option value="DE">Delaware</option>
                            <option value="FL">Florida</option>
                            <option value="GA">Georgia</option>
                            <option value="HI">Hawaii</option>
                            <option value="ID">Idaho</option>
                            <option value="IL">Illinois</option>
                            <option value="IN">Indiana</option>
                            <option value="IA">Iowa</option>
                            <option value="KS">Kansas</option>
                            <option value="KY">Kentucky</option>
                            <option value="LA">Louisiana</option>
                            <option value="ME">Maine</option>
                            <option value="MD">Maryland</option>
                            <option value="MA">Massachusetts</option>
                            <option value="MI">Michigan</option>
                            <option value="MN">Minnesota</option>
                            <option value="MS">Mississippi</option>
                            <option value="MO">Missouri</option>
                            <option value="MT">Montana</option>
                            <option value="NE">Nebraska</option>
                            <option value="NV">Nevada</option>
                            <option value="NH">New Hampshire</option>
                            <option value="NJ">New Jersey</option>
                            <option value="NM">New Mexico</option>
                            <option value="NY">New York</option>
                            <option value="NC">North Carolina</option>
                            <option value="ND">North Dakota</option>
                            <option value="OH">Ohio</option>
                            <option value="OK">Oklahoma</option>
                            <option value="OR">Oregon</option>
                            <option value="PA">Pennsylvania</option>
                            <option value="RI">Rhode Island</option>
                            <option value="SC">South Carolina</option>
                            <option value="SD">South Dakota</option>
                            <option value="TN">Tennessee</option>
                            <option value="TX">Texas</option>
                            <option value="UT">Utah</option>
                            <option value="VT">Vermont</option>
                            <option value="VA">Virginia</option>
                            <option value="WA">Washington</option>
                            <option value="WV">West Virginia</option>
                            <option value="WI">Wisconsin</option>
                            <option value="WY">Wyoming</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="zip">ZIP</label>
                        <input type="text" name="zip" id="zip">
                    </div>
                </div>
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="sqFt">Square Ft</label>
                        <input type="text" name="sqFt" id="sqFt"/>
                    </div>
                </div>
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="year">Year</label>
                        <input type="text" name="year" id="year"/>
                    </div>
                </div>
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="min">Minutes from Subway</label>
                        <input type="text" name="min" id="min"/>
                    </div>
                </div>

                <input type="submit" class="waves-effect waves-light btn"/>
            </form>
        </div>
    {% endif %}
{% endblock %}

sublet/app/templates/app/addlisting.html
{% extends 'app/base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="container center">
            <form action="{% url 'app:addListing' %}" method="post">
            {% csrf_token %}
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="title">Title</label>
                        <input type="text" name="title" id="title">
                    </div>
                </div>

                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="price">Price Per Day</label>
                        <input type="text" name="price" id="price">
                    </div>
                    <div class="col s3">
                        <button class="waves-effect waves-light btn" id="estimate" type="button">Suggested Price</button>
                    </div>
                </div>
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="duration">Duration</label>
                        <input type="text" name="duration" id="duration">
                    </div>
                </div>
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="apartment_sel">Select Apartment:</label>
                        <select name="apartment" id="apartment_sel" class="browser-default">
                            {% for apartment in apartments %}
                                <option data-val="{{ apartment.get_address }}" value="{{ apartment.id }}">{{ apartment }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <br>
                <input type="submit" class="waves-effect waves-light btn"/>
            </form>
        </div>
    {% endif %}
    <script>
        $('#estimate').click(function(e){
            e.preventDefault();
            var csrftoken = getCookie('csrftoken');
{#                var apartments = {{ apartments_json|safe }};#}
{#                for (apartment in apartments)#}
{#                console.log( $.trim($("#apartment_sel").text()));#}

            var apartments = {{ json_apartments|safe }};
            var sqft;
            var year;
            var min_from_subway;
            for (var i=0; i<apartments.length; i++ ){
                console.log(apartments[i]);
                var trim_text =  ($("#apartment_sel option:selected").text()).trim();
                console.log( trim_text );
                if (apartments[i][0] == trim_text){
                    console.log("Success");
                    sqft = apartments[i][1];
                    year = apartments[i][2];
                    min_from_subway = apartments[i][3];
                    break;
                }
            }
            console.log(sqft,year,min_from_subway);
            $.ajax({
                url: "{% url 'app:estimate' %}",
                type : "POST", // http method
                data : {
                    csrfmiddlewaretoken : csrftoken,
                    sqft : sqft,
                    year : year,
                    min_from_subway : min_from_subway
                },
                success : function(json){
                    var price = json['success'];
                    $("#price").val(price);
{#                    alert(price); //check data sent back#}
                },
                // handle a non-successful response
                error : function(xhr,errmsg,err) {
                    console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                }

            });
        });
    </script>
{% endblock %}

sublet/app/templates/app/apartment.html
{% extends 'app/base.html' %}
{% block content %}
    <div class="container center">
        <h2>Address: {{ apartment.get_address }}</h2>
        <h2>Sq. Ft.: {{ apartment.sqFt }}</h2>
        <h2>Year Built: {{ apartment.year }}</h2>
        <h2>Min. From Subway: {{ apartment.min_from_subway }}</h2>
        <h2>Listings:</h2>
        {%  for listing in apartment.listings_owned.all %}
        <h3><a href="{% url 'app:listing' listing.user_pk listing.id %}">{{ listing.title }}</a></h3>
        {% endfor %}
    </div>

{% endblock %}

sublet/app/templates/app/apartments.html
{% extends 'app/base.html' %}
{% block content %}
    <div class="container">
        <h2 class="center">All Apartments</h2>
        <table class="bordered highlight">
            <thead>
                <tr>
                  <th data-field="address">Address</th>
                  <th data-field="sqFt">Sq. Ft.</th>
                  <th data-field="year">Year Built</th>
                  <th data-field="min">Min. From Subway</th>
                </tr>
            </thead>

            <tbody>
            {% for apartment in apartments %}
            <tr>
                <td><a href="{% url 'app:apartment' apartment.user_pk apartment.id %}">{{ apartment.get_address }}</a></td>
                <td>{{ apartment.sqFt }}</td>
                <td>{{ apartment.year }}</td>
                <td>{{ apartment.min_from_subway }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

sublet/app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'app/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'app/css/materialize.min.css' %}">
        <script src="{% static 'app/js/jquery-2.1.4.min.js' %}"></script>
        <script src="{% static 'app/js/materialize.js' %}"></script>
        <title>Sublet Portal</title>

    </head>
    <body>
        <nav class="deep-purple darken-4" role="navigation">
            <div class="nav-wrapper container">
                <a id="logo-container" href="{% url 'app:home' %}" class="brand-logo center">Sublet Portal</a>
                <ul class="left hide-on-med-and-down">
                    <li><a href="{% url 'app:apartments' %}">Apartments</a></li>
                    <li><a href="{% url 'app:listings' %}">Listings</a></li>
                    <li><a href="{% url 'app:bookings' %}">Bookings</a></li>
                </ul>
                <ul class="right hide-on-med-and-down">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'app:profile' %}">{{ user.username | capfirst }}</a></li>
                    <li><a href="{% url 'app:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'app:login' %}">Login</a></li>
                    <li><a href="{% url 'app:register' %}">Register</a></li>
                    {% endif %}
                </ul>
                <ul id="nav-mobile" class="side-nav">
                    <li><a href="{% url 'app:apartments' %}">Apartments</a></li>
                    <li><a href="{% url 'app:listings' %}">Listings</a></li>
                    <li><a href="{% url 'app:bookings' %}">Bookings</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'app:profile' %}">{{ user.username | capfirst }}</a></li>
                    <li><a href="{% url 'app:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'app:login' %}">Login</a></li>
                    <li><a href="{% url 'app:register' %}">Register</a></li>
                    {% endif %}
                </ul>
                <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
            </div>
        </nav>

        <div style="margin-top: 20px;">{% block content %}{% endblock %}</div>
    <script>
        $(document).ready(function() {
            $('select').material_select();
            $(".button-collapse").sideNav();
            $('ul.tabs').tabs();
        });
    </script>
    <script type="text/javascript" src="{% static 'app/js/main.js' %}"></script>
    </body>
</html>

sublet/app/templates/app/bookings.html
{% extends 'app/base.html' %}
{% block content %}
    <div class="container">
        <h2 class="center">All Bookings</h2>
        <table class="bordered highlight">
            <thead>
                <tr>
                    <th data-field="booker">Booker</th>
                    <th data-field="title">Title</th>
                    <th data-field="price">Price</th>
                    <th data-field="duration">Duration</th>
                    <th data-field="date">Date Booked</th>
                </tr>
            </thead>

            <tbody>
            {% for booking in bookings %}
            <tr>
                <td>{{ booking.user.username }}</td>
                <td>{{ booking.listing.title }}</td>
                <td>{{ booking.listing.price }}</td>
                <td>{{ booking.duration }} Day{{ listing.duration|pluralize }}</td>
                <td>{{ booking.date }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

sublet/app/templates/app/editlisting.html
{% extends 'app/base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="container center">
            <form action="{% url 'app:editListing' listing.user_pk listing.id %}" method="post">
            {% csrf_token %}
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="title">Title</label>
                        <input type="text" name="title" id="title" value="{{ listing.title }}">
                    </div>
                </div>

                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="price">Price Per Day</label>
                        <input type="text" name="price" id="price" value="{{ listing.price }}">
                    </div>
                    <div class="col s3">
                        <button class="waves-effect waves-light btn" id="estimate" type="button">Suggested Price</button>
                    </div>
                </div>
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="duration">Duration</label>
                        <input type="text" name="duration" id="duration" value="{{ listing.duration }}">
                    </div>
                </div>
                <div class="row">
                    <div class="offset-s3 col s6">
                        <label for="apartment_sel">Select Apartment:</label>
                        <select name="apartment" id="apartment_sel" class="browser-default">
                            <option data-val="{{ apartment.get_address }}" value="{{ apartment.id }}">{{ apartment }}</option>
                        </select>
                    </div>
                </div>
                <br>
                <input type="submit" class="waves-effect waves-light btn"/>
            </form>
        </div>
    {% endif %}
    <script>
        $('#estimate').click(function(e){
            e.preventDefault();
            var csrftoken = getCookie('csrftoken');
            var apartment = {{ json_apartment|safe }};
            var sqft;
            var year;
            var min_from_subway;
            console.log(apartment);
            console.log("Success");
            sqft = apartment[1];
            year = apartment[2];
            min_from_subway = apartment[3];
            console.log(sqft,year,min_from_subway);
            $.ajax({
                url: "{% url 'app:estimate' %}",
                type : "POST", // http method
                data : {
                    csrfmiddlewaretoken : csrftoken,
                    sqft : sqft,
                    year : year,
                    min_from_subway : min_from_subway
                },
                success : function(json){
                    var price = json['success'];
                    $("#price").val(price);
{#                    alert(price); //check data sent back#}
                },
                // handle a non-successful response
                error : function(xhr,errmsg,err) {
                    console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                }
            });
        });
    </script>
{% endblock %}

sublet/app/templates/app/home.html
{% extends 'app/base.html' %}
{% block content %}
<div class="section no-pad-bot" id="index-banner">
    <div class="container">
        <br><br>
        <h1 class="header center green-text text-darken-1">Hello, {% if user.is_authenticated %}{{ user.username | capfirst }}{% else %}Guest {% endif %}</h1>
        <div class="row center">
            <h5 class="header col s12 light">
                {% if user.is_authenticated %}
                    Get started by adding apartments, listings, or bookings. View any of these categories by navigating to the top left corner and clicking one
                {% else %}Sign up or log in to help you sublet or rent an apartment{% endif %}</h5>
        </div>
        <div class="row center">
            <div class="col m6 s12"><a href="{% url 'app:addApartment' %}" class="btn-large waves-effect waves-light green darken-1">Add Apartment</a></div>
            <div class="col m6 s12"><a href="{% url 'app:addListing' %}" class="btn-large waves-effect waves-light green darken-1">Add Listing</a></div>
        </div>
        <br><br>
    </div>
</div>

{%  endblock %}

sublet/app/templates/app/listing.html
{% extends 'app/base.html' %}
{% block content %}
    <div class="container center">
        <h2>Title: {{ listing.title }}</h2>
        <h2>Price: {{ listing.price }}</h2>
        <h2>Duration: {{ listing.duration }}</h2>
        <h2>Date Listed: {{ listing.duration }}</h2>
        {% if user.is_authenticated and not listing.is_booked %}
        <form action="{% url 'app:book' %}" method="post">
        {% csrf_token %}
        <button type="submit" id="submit" class="waves-effect waves-light btn">Book!</button>
        {% if user.id == listing.user_pk %}
        <a href="{% url 'app:editListing' listing.user_pk listing.id %}" class="waves-effect waves-light btn">Edit</a>
        {% endif %}
        </form>
        <script>
            $('#submit').click(function(e){
                e.preventDefault();
                var csrftoken = getCookie('csrftoken');
                var shard_id = {{ listing.user_pk }};
                var list_id = {{ listing.id }};
                $.ajax({
                    url: "{% url 'app:book' %}",
                    type : "POST", // http method
                    data : {
                        csrfmiddlewaretoken : csrftoken,
                        shard_id: shard_id,
                        list_id: list_id
                    },
                    success : function(){
                        alert("successfully booked"); //check data sent back
                    },
                    // handle a non-successful response
                    error : function(xhr,errmsg,err) {
                        console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                    }

                });
            });
        </script>
    {% endif %}
    </div>




{% endblock %}

sublet/app/templates/app/listings.html
{% extends 'app/base.html' %}
{% block content %}
    <div class="container">
        <h2 class="center">All Listings</h2>
        <table class="bordered highlight">
            <thead>
                <tr>
                  <th data-field="title">Title</th>
                  <th data-field="price">Price</th>
                  <th data-field="duration">Duration</th>
                  <th data-field="date">Date Listed</th>
                </tr>
            </thead>

            <tbody>
            {% for listing in listings %}
            <tr>
                <td><a href="{% url 'app:listing' listing.user_pk listing.id %}">{{ listing.title }}</a></td>
                <td>{{ listing.price }}</td>
                <td>{{ listing.duration }} Day{{ listing.duration|pluralize }}</td>
                <td>{{ listing.date }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

sublet/app/templates/app/login.html
{% extends 'app/base.html' %}
{% block content %}
    <div class="container center">
        <form method="post" action="{% url 'app:login' %}">
        {% csrf_token %}
            <div class="row">
                <div class="offset-s3 col s6">
                    <label for="username">Username</label>
                    <input id="username" type="text" name="username" />
                </div>
            </div>
            <div class="row">
                <div class="offset-s3 col s6">
                    <label for="password">Username</label>
                    <input id="password" type="password" name="password" />
                </div>
            </div>
            <input type="submit" class="waves-effect waves-light btn"/>
        </form>
    </div>

{% endblock %}

sublet/app/templates/app/profile.html
{% extends 'app/base.html' %}
{% block content %}

{% if user.is_authenticated %}
    <div class="row container" style="margin-top: 50px;">
        <div class="col s12">
          <ul class="tabs">
            <li class="tab col s3"><a class="active" href="#test1">Apartments</a></li>
            <li class="tab col s3"><a href="#test2">Open Listings</a></li>
            <li class="tab col s3"><a href="#test3">Closed Listings</a></li>
            <li class="tab col s3"><a href="#test4">Bookings</a></li>
          </ul>
        </div>
        <div id="test1" class="col s12 container" style="margin-top: 10px;">
            <table class="bordered highlight">
                <thead>
                    <tr>
                      <th data-field="street">Street</th>
                      <th data-field="city">City</th>
                      <th data-field="state">State</th>
                      <th data-field="zip">ZIP</th>
                      <th data-field="sqFt">Sq. Ft.</th>
                      <th data-field="year">Year Built</th>
                      <th data-field="min">Min. From Subway</th>
                    </tr>
                </thead>
                <tbody>
                {% for apartment in apartments %}
                    <tr>
                        <td>{{ apartment.street }}</td>
                        <td>{{ apartment.city }}</td>
                        <td>{{ apartment.state }}</td>
                        <td>{{ apartment.zip }}</td>
                        <td>{{ apartment.sqFt }}</td>
                        <td>{{ apartment.year }}</td>
                        <td>{{ apartment.min_from_subway }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div id="test2" class="col s12 container" style="margin-top: 10px;">
            <table class="bordered highlight">
                <thead>
                    <tr>
                      <th data-field="title">Title</th>
                      <th data-field="price">Price</th>
                      <th data-field="duration">Duration</th>
                      <th data-field="date">Date Listed</th>
                    </tr>
                </thead>

                <tbody>
                {% for listing in open_listings %}
                <tr>
                    <td><a href="{% url 'app:listing' listing.user_pk listing.id %}">{{ listing.title }}</a></td>
                    <td>{{ listing.price }}</td>
                    <td>{{ listing.duration }} Day{{ listing.duration|pluralize }}</td>
                    <td>{{ listing.date }}</td>
                    <td><a href="{% url 'app:editListing' listing.user_pk listing.id %}" class="waves-effect waves-light btn">Edit Listing</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div id="test3" class="col s12 container" style="margin-top: 10px;">
            <table class="bordered highlight">
                <thead>
                    <tr>
                      <th data-field="title">Title</th>
                      <th data-field="price">Price</th>
                      <th data-field="duration">Duration</th>
                      <th data-field="date">Date Listed</th>
                    </tr>
                </thead>

                <tbody>
                {% for listing in closed_listings %}
                <tr>
                    <td><a href="{% url 'app:listing' listing.user_pk listing.id %}">{{ listing.title }}</a></td>
                    <td>{{ listing.price }}</td>
                    <td>{{ listing.duration }} Day{{ listing.duration|pluralize }}</td>
                    <td>{{ listing.date }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div id="test4" class="col s12 container" style="margin-top: 10px;">
            <table class="bordered highlight">
                <thead>
                    <tr>
                        <th data-field="booker">Booker</th>
                        <th data-field="title">Title</th>
                        <th data-field="price">Price</th>
                        <th data-field="duration">Duration</th>
                        <th data-field="date">Date Booked</th>
                    </tr>
                </thead>

                <tbody>
                {% for booking in bookings %}
                <tr>
                    <td>{{ booking.user.username }}</td>
                    <td>{{ booking.listing.title }}</td>
                    <td>{{ booking.listing.price }}</td>
                    <td>{{ booking.duration }} Day{{ listing.duration|pluralize }}</td>
                    <td>{{ booking.date }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>




{% endif %}
{%  endblock %}

sublet/app/templates/app/register.html
{% extends 'app/base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        <p>You have already registered, {{ user.username }}</p>
    {% else %}
    <div class="container center">
        <form method="post" action="{% url 'app:register' %}">
        {% csrf_token %}
            <div class="row">
                <div class="offset-s3 col s6">
                    <label for="username">Username</label>
                    <input type="text" name="username" id="username" />
                </div>
            </div>
            <div class="row">
                <div class="offset-s3 col s6">
                    <label for="email">Email</label>
                    <input type="email" name="email" id="email" />
                </div>
            </div>
            <div class="row">
                <div class="offset-s3 col s6">
                    <label for="password">Password</label>
                    <input type="password" name="password" id="password" />
                </div>
            </div>

            <input type="submit" class="waves-effect waves-light btn"/>
        </form>
    </div>

    {% endif %}
{% endblock %}